### ISSUE TITLE
YouTube loader keep spining

### ISSUE THREAD

**Issue by Soullighter** [RavanH/easy-fancybox#3]
There is a bug when youtube is in anchor, and pop-up with fancybox, loader keep spinning and won't go off. I know YT change their API, so prob video need to autoplay but that is not a case, so spinner keep spinning on and on...
Chrome console error
https://ibb.co/ecCEtT

**Comment by RavanH** [comment]
Hi, this looks like a conflict with other script. The url should be a string which in turn should make indexOf a function... I've tested with jQuery 1.11.1 since you seem to be using that. In itself that version is compatible but I wonder: are you on the latest WordPress version? If so, then that jQuery must be coming from another plugin or your theme and being added as a second jQuery library, it might be causing the conflict.

Any chance you can share your site URL so I can see it live? If you want to keep it private, you can use the contact form on https://status301.net/contact-en/

Thanks :)
